---
version: "3.8"
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.37.5
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
  prober:
    image: cloudprober/cloudprober:v0.11.2
    volumes:
      - ./prober/cloudprober.cfg:/etc/cloudprober.cfg:ro
  squid:
    image: hsmtkk/probable-enigma:squid-4.16
    volumes:
      - ./squid/squid.conf:/usr/local/squid/etc/squid.conf:ro
      - squid_log:/usr/local/squid/var/logs
  promtail:
    image: grafana/promtail:2.2.1
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - squid_log:/usr/local/squid/var/logs:ro
  prometheus:
    image: prom/prometheus:v2.28.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  loki:
    image: grafana/loki:2.2.1
volumes:
  squid_log:
